"""General code assistant runtime stub.

This skill is intentionally lightweight: it does not call an LLM itself.
The planner/fallback layer is responsible for generating the code and
passing it in via the `generated_code` parameter. This keeps the skill
interface stable and avoids baking LLM details into the runtime.
"""

import json
import sys


def main(skill_inputs: dict) -> dict:
    """Return the generated code with metadata."""
    request = skill_inputs.get("request", "")
    language = skill_inputs.get("language", "python")
    generated_code = skill_inputs.get("generated_code", "")
    explanation = skill_inputs.get("explanation", "")

    if not generated_code:
        return {
            "code": "",
            "explanation": explanation or "No code was generated.",
            "warnings": "This skill requires a pre-generated code payload.",
            "language": language,
            "request": request,
        }

    return {
        "code": generated_code,
        "explanation": explanation,
        "warnings": (
            "Review this code carefully before execution. "
            "It was generated by an LLM and may modify files."
        ),
        "language": language,
        "request": request,
    }


if __name__ == "__main__":
    skill_inputs = json.loads(sys.argv[1])
    result = main(skill_inputs)
    print(json.dumps(result))
