"""add execution_trace_nodes_table

Revision ID: 1bd3eff3b8c5
Revises: 5fd996862269
Create Date: 2026-07-02 15:05:51.855065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd3eff3b8c5'
down_revision: Union[str, None] = '5fd996862269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'execution_trace_nodes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('trace_id', sa.String(), nullable=False),
        sa.Column('node_id', sa.String(), nullable=False),
        sa.Column('parent_id', sa.String(), nullable=True),
        sa.Column('node_type', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('ended_at', sa.DateTime(), nullable=True),
        sa.Column('inputs_json', sa.Text(), nullable=False),
        sa.Column('outputs_json', sa.Text(), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('logs_json', sa.Text(), nullable=False),
        sa.Column('metadata_json', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['trace_id'], ['execution_traces.trace_id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('trace_id', 'node_id')
    )
    op.create_index(
        op.f('ix_execution_trace_nodes_trace_id'),
        'execution_trace_nodes',
        ['trace_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_execution_trace_nodes_trace_id'),
        table_name='execution_trace_nodes',
    )
    op.drop_table('execution_trace_nodes')
    # ### end Alembic commands ###
