"""add analysis_reports_table

Revision ID: 5afa6a391fc2
Revises: 1bd3eff3b8c5
Create Date: 2026-07-02 15:32:32.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afa6a391fc2'
down_revision: Union[str, None] = '1bd3eff3b8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'analysis_reports',
        sa.Column('report_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('project_name', sa.String(), nullable=False),
        sa.Column('analysis_type', sa.String(), nullable=False),
        sa.Column('author', sa.String(), nullable=False),
        sa.Column('tags_json', sa.Text(), nullable=False),
        sa.Column('parameters_json', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('sections_json', sa.Text(), nullable=False),
        sa.Column('steps_json', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(
        op.f('ix_analysis_reports_analysis_type'),
        'analysis_reports',
        ['analysis_type'],
        unique=False,
    )
    op.create_index(
        op.f('ix_analysis_reports_project_name'),
        'analysis_reports',
        ['project_name'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_analysis_reports_project_name'),
        table_name='analysis_reports',
    )
    op.drop_index(
        op.f('ix_analysis_reports_analysis_type'),
        table_name='analysis_reports',
    )
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
