"""initial schema

Revision ID: 5fd996862269
Revises: 
Create Date: 2026-06-15 19:14:17.239795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd996862269'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_traces',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('nodes_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index(op.f('ix_execution_traces_project_id'), 'execution_traces', ['project_id'], unique=False)
    op.create_index(op.f('ix_execution_traces_session_id'), 'execution_traces', ['session_id'], unique=False)
    op.create_index(op.f('ix_execution_traces_status'), 'execution_traces', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('task_tree_json', sa.Text(), nullable=True),
    sa.Column('working_memory_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('resume_task_id', sa.String(), nullable=True),
    sa.Column('resume_choice', sa.String(), nullable=True),
    sa.Column('resume_parameters_json', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_plan_id'), 'jobs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_session_id'), 'jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('plans',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('intent_analysis_type', sa.String(), nullable=False),
    sa.Column('intent_complexity', sa.String(), nullable=True),
    sa.Column('plan_result_json', sa.Text(), nullable=False),
    sa.Column('task_tree_json', sa.Text(), nullable=False),
    sa.Column('working_memory_json', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('parent_plan_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_plans_parent_plan_id'), 'plans', ['parent_plan_id'], unique=False)
    op.create_index(op.f('ix_plans_project_id'), 'plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_plans_session_id'), 'plans', ['session_id'], unique=False)
    op.create_index(op.f('ix_plans_status'), 'plans', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('scheduled_job_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('trigger_time', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_job_runs_job_name'), 'scheduled_job_runs', ['job_name'], unique=False)
    op.create_index(op.f('ix_scheduled_job_runs_status'), 'scheduled_job_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_job_runs_status'), table_name='scheduled_job_runs')
    op.drop_index(op.f('ix_scheduled_job_runs_job_name'), table_name='scheduled_job_runs')
    op.drop_table('scheduled_job_runs')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_plans_status'), table_name='plans')
    op.drop_index(op.f('ix_plans_session_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_project_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_parent_plan_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_session_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_plan_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_execution_traces_status'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_session_id'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_project_id'), table_name='execution_traces')
    op.drop_table('execution_traces')
    # ### end Alembic commands ###
