# Utility Functions for decoupleR Analysis
# Generated by refactoring based on decoupleR best practices

# ============================================================================
# Installation and Validation
# ============================================================================

#' Check decoupleR installation and dependencies
#'
#' @return List with installation status
#' @export
check_decoupler_installation <- function() {
  result <- list(
    decoupler_installed = FALSE,
    seurat_installed = FALSE,
    progeny_installed = FALSE,
    dorothea_installed = FALSE,
    omnipathr_installed = FALSE,
    version = NULL,
    errors = character()
  )

  # Check decoupleR
  if (requireNamespace("decoupleR", quietly = TRUE)) {
    result$decoupler_installed <- TRUE
    result$version <- packageVersion("decoupleR")
  } else {
    result$errors <- c(result$errors, "decoupleR not installed")
  }

  # Check optional packages
  result$seurat_installed <- requireNamespace("Seurat", quietly = TRUE)
  result$progeny_installed <- requireNamespace("progeny", quietly = TRUE)
  result$dorothea_installed <- requireNamespace("dorothea", quietly = TRUE)
  result$omnipathr_installed <- requireNamespace("OmnipathR", quietly = TRUE)

  return(result)
}

#' Validate input matrix for decoupleR analysis
#'
#' @param mat Expression matrix (genes x samples)
#' @return List with validation results
#' @export
validate_decoupler_matrix <- function(mat) {
  result <- list(
    valid = TRUE,
    n_genes = NULL,
    n_samples = NULL,
    warnings = character(),
    errors = character()
  )

  # Check if matrix
  if (!is.matrix(mat) && !is(mat, "Matrix")) {
    result$valid <- FALSE
    result$errors <- c(result$errors, "Input must be a matrix or sparse Matrix")
    return(result)
  }

  result$n_genes <- nrow(mat)
  result$n_samples <- ncol(mat)

  # Check for NAs
  na_count <- sum(is.na(mat))
  if (na_count > 0) {
    result$warnings <- c(result$warnings,
                         sprintf("Matrix contains %d NA values", na_count))
  }

  # Check for negative values
  if (min(mat, na.rm = TRUE) < 0) {
    result$warnings <- c(result$warnings,
                         "Matrix contains negative values; some methods may not be appropriate")
  }

  # Check dimensions
  if (result$n_genes < 100) {
    result$warnings <- c(result$warnings,
                         "Few genes detected; network coverage may be poor")
  }

  return(result)
}

#' Validate network for decoupleR analysis
#'
#' @param net Network data frame
#' @return List with validation results
#' @export
validate_decoupler_network <- function(net) {
  result <- list(
    valid = TRUE,
    n_sources = NULL,
    n_targets = NULL,
    warnings = character(),
    errors = character()
  )

  required_cols <- c("source", "target")
  optional_weight <- "weight" %in% colnames(net)
  optional_mor <- "mor" %in% colnames(net)
  optional_likelihood <- "likelihood" %in% colnames(net)

  # Check required columns
  missing_cols <- setdiff(required_cols, colnames(net))
  if (length(missing_cols) > 0) {
    result$valid <- FALSE
    result$errors <- c(result$errors,
                       sprintf("Missing required columns: %s",
                               paste(missing_cols, collapse = ", ")))
    return(result)
  }

  result$n_sources <- length(unique(net$source))
  result$n_targets <- length(unique(net$target))

  # Check for numeric weight/mor if present
  if (optional_weight && !is.numeric(net$weight)) {
    result$warnings <- c(result$warnings, "Weight column is not numeric")
  }

  if (optional_mor && !is.numeric(net$mor)) {
    result$warnings <- c(result$warnings, "MoR column is not numeric")
  }

  return(result)
}

# ============================================================================
# Network Utilities
# ============================================================================

#' Filter network by size (number of targets per source)
#'
#' @param net Network data frame
#' @param minsize Minimum number of targets per source
#' @param maxsize Maximum number of targets per source (NULL for no limit)
#' @return Filtered network
#' @export
filter_network_by_size <- function(net, minsize = 5, maxsize = NULL) {
  source_counts <- table(net$source)

  valid_sources <- names(source_counts)[source_counts >= minsize]

  if (!is.null(maxsize)) {
    valid_sources <- intersect(valid_sources,
                               names(source_counts)[source_counts <= maxsize])
  }

  filtered_net <- net[net$source %in% valid_sources, ]

  message(sprintf("Filtered network: %d sources -> %d sources",
                  length(unique(net$source)),
                  length(unique(filtered_net$source))))

  return(filtered_net)
}

#' Filter network by confidence level
#'
#' @param net Network data frame with confidence/level column
#' @param min_level Minimum confidence level to include
#' @return Filtered network
#' @export
filter_network_by_confidence <- function(net, min_level = "A") {
  if (!"confidence" %in% colnames(net) && !"level" %in% colnames(net)) {
    warning("No confidence/level column found; returning original network")
    return(net)
  }

  conf_col <- ifelse("confidence" %in% colnames(net), "confidence", "level")

  # Define confidence ordering
  conf_order <- c("A" = 4, "B" = 3, "C" = 2, "D" = 1, "E" = 0,
                  "High" = 3, "Medium" = 2, "Low" = 1)

  min_score <- conf_order[min_level]

  if (is.na(min_score)) {
    warning("Unknown confidence level; returning original network")
    return(net)
  }

  source_scores <- conf_order[net[[conf_col]]]
  filtered_net <- net[source_scores >= min_score, ]

  message(sprintf("Confidence filter: %d -> %d interactions",
                  nrow(net), nrow(filtered_net)))

  return(filtered_net)
}

#' Check gene overlap between matrix and network
#'
#' @param mat Expression matrix
#' @param net Network data frame
#' @return List with overlap statistics
#' @export
check_gene_overlap <- function(mat, net) {
  mat_genes <- rownames(mat)
  net_genes <- unique(net$target)

  overlap <- intersect(mat_genes, net_genes)
  mat_only <- setdiff(mat_genes, net_genes)
  net_only <- setdiff(net_genes, mat_genes)

  result <- list(
    n_mat_genes = length(mat_genes),
    n_net_genes = length(net_genes),
    n_overlap = length(overlap),
    overlap_fraction = length(overlap) / length(net_genes),
    mat_only_genes = mat_only,
    net_only_genes = net_only
  )

  return(result)
}

#' Convert between network formats
#'
#' @param net Input network
#' @param to_format Target format ("decoupler", "wide", "igraph")
#' @return Network in target format
#' @export
convert_network_format <- function(net, to_format = "decoupler") {
  if (to_format == "decoupler") {
    # Already in decoupleR format (tall)
    return(net)
  }

  if (to_format == "wide") {
    # Convert to wide format (sources x targets)
    if ("weight" %in% colnames(net)) {
      val_col <- "weight"
    } else if ("mor" %in% colnames(net)) {
      val_col <- "mor"
    } else {
      stop("No weight or mor column found for wide conversion")
    }

    wide_net <- net %>%
      dplyr::select(source, target, !!rlang::sym(val_col)) %>%
      tidyr::pivot_wider(names_from = target, values_from = !!rlang::sym(val_col), values_fill = 0) %>%
      as.data.frame()
    rownames(wide_net) <- wide_net$source
    wide_net$source <- NULL

    return(wide_net)
  }

  if (to_format == "igraph") {
    if (!requireNamespace("igraph", quietly = TRUE)) {
      stop("igraph package required")
    }

    g <- igraph::graph_from_data_frame(
      d = net[, c("source", "target")],
      directed = TRUE
    )

    # Add edge attributes if present
    if ("weight" %in% colnames(net)) {
      igraph::E(g)$weight <- net$weight
    }
    if ("mor" %in% colnames(net)) {
      igraph::E(g)$mor <- net$mor
    }

    return(g)
  }

  stop(sprintf("Unknown format: %s", to_format))
}

#' Show network summary statistics
#'
#' @param net Network data frame
#' @return List with summary statistics
#' @export
show_network_summary <- function(net) {
  sources <- unique(net$source)
  targets <- unique(net$target)

  # Calculate targets per source
  targets_per_source <- table(net$source)

  summary <- list(
    n_sources = length(sources),
    n_targets = length(targets),
    n_interactions = nrow(net),
    min_targets_per_source = min(targets_per_source),
    max_targets_per_source = max(targets_per_source),
    median_targets_per_source = median(targets_per_source),
    top_sources_by_targets = head(sort(targets_per_source, decreasing = TRUE), 10)
  )

  return(summary)
}

# ============================================================================
# Result Utilities
# ============================================================================

#' Get top activities from decoupleR results
#'
#' @param acts Activity results from decoupleR
#' @param by Source column name
#' @param n_top Number of top sources to return
#' @return Data frame with top activities
#' @export
get_top_activities <- function(acts, by = "source", n_top = 10) {
  # Average across conditions/samples
  avg_acts <- acts %>%
    dplyr::group_by(!!rlang::sym(by)) %>%
    dplyr::summarise(mean_score = mean(score, na.rm = TRUE),
                     sd_score = sd(score, na.rm = TRUE)) %>%
    dplyr::arrange(dplyr::desc(abs(mean_score)))

  return(head(avg_acts, n_top))
}

#' Get top activities per sample/condition
#'
#' @param acts Activity results from decoupleR
#' @param by Source column name
#' @param n_top Number of top sources per condition
#' @return Data frame with top activities per condition
#' @export
get_top_activities_per_condition <- function(acts, by = "source",
                                              n_top = 5) {
  top_by_cond <- acts %>%
    dplyr::group_by(condition) %>%
    dplyr::slice_max(order_by = abs(score), n = n_top) %>%
    dplyr::ungroup()

  return(top_by_cond)
}

#' Filter results by score threshold
#'
#' @param acts Activity results
#' @param score_threshold Minimum absolute score
#' @return Filtered results
#' @export
filter_results_by_score <- function(acts, score_threshold = 1) {
  filtered <- acts %>%
    dplyr::filter(abs(score) >= score_threshold)

  message(sprintf("Filtered: %d -> %d records",
                  nrow(acts), nrow(filtered)))

  return(filtered)
}

#' Summarize decoupleR results (lightweight)
#'
#' @param acts Activity results
#' @return List with summary statistics
#' @export
summarize_activities_light <- function(acts) {
  summary <- list(
    n_records = nrow(acts),
    n_sources = length(unique(acts$source)),
    n_conditions = length(unique(acts$condition)),
    score_range = range(acts$score, na.rm = TRUE),
    score_mean = mean(acts$score, na.rm = TRUE),
    score_sd = sd(acts$score, na.rm = TRUE)
  )

  # Count by statistic
  if ("statistic" %in% colnames(acts)) {
    summary$by_statistic <- table(acts$statistic)
  }

  return(summary)
}

# ============================================================================
# Differential Analysis
# ============================================================================

#' Calculate differential activities between conditions
#'
#' @param acts Activity results
#' @param condition_col Column containing condition labels
#' @param cond1 First condition
#' @param cond2 Second condition
#' @param statistic Which statistic to use (if multiple)
#' @return Data frame with differential analysis results
#' @export
get_differential_activities <- function(acts,
                                        condition_col = "condition",
                                        cond1, cond2,
                                        statistic = NULL) {
  # Filter to specific statistic if provided
  if (!is.null(statistic) && "statistic" %in% colnames(acts)) {
    acts <- acts[acts$statistic == statistic, ]
  }

  # Get data for each condition
  cond1_data <- acts[acts[[condition_col]] == cond1, ]
  cond2_data <- acts[acts[[condition_col]] == cond2, ]

  # Merge by source
  merged <- merge(cond1_data, cond2_data, by = "source",
                  suffixes = c("_1", "_2"))

  # Calculate difference
  merged$diff <- merged$score_1 - merged$score_2
  merged$mean_score <- (merged$score_1 + merged$score_2) / 2

  # Sort by absolute difference
  merged <- merged[order(abs(merged$diff), decreasing = TRUE), ]

  return(merged[, c("source", "score_1", "score_2", "diff", "mean_score")])
}

#' Compare activities across multiple conditions
#'
#' @param acts Activity results
#' @param condition_col Column containing condition labels
#' @param statistic Which statistic to use
#' @return Data frame with comparison results
#' @export
compare_activities_across_conditions <- function(acts,
                                                  condition_col = "condition",
                                                  statistic = NULL) {
  # Filter to specific statistic if provided
  if (!is.null(statistic) && "statistic" %in% colnames(acts)) {
    acts <- acts[acts$statistic == statistic, ]
  }

  # Reshape to wide format
  wide_acts <- reshape2::dcast(acts, source ~ condition,
                                value.var = "score")

  # Calculate summary statistics
  score_cols <- setdiff(colnames(wide_acts), "source")
  wide_acts$mean_score <- rowMeans(wide_acts[, score_cols], na.rm = TRUE)
  wide_acts$sd_score <- apply(wide_acts[, score_cols], 1, sd, na.rm = TRUE)
  wide_acts$max_score <- apply(wide_acts[, score_cols], 1, max, na.rm = TRUE)
  wide_acts$min_score <- apply(wide_acts[, score_cols], 1, min, na.rm = TRUE)
  wide_acts$range <- wide_acts$max_score - wide_acts$min_score

  # Sort by range (most variable across conditions)
  wide_acts <- wide_acts[order(wide_acts$range, decreasing = TRUE), ]

  return(wide_acts)
}

#' Find condition-specific activities
#'
#' @param acts Activity results
#' @param condition_col Column containing condition labels
#' @param statistic Which statistic to use
#' @param threshold Activity threshold for specificity
#' @return List with condition-specific activities
#' @export
find_condition_specific_activities <- function(acts,
                                               condition_col = "condition",
                                               statistic = NULL,
                                               threshold = 0.5) {
  # Filter to specific statistic if provided
  if (!is.null(statistic) && "statistic" %in% colnames(acts)) {
    acts <- acts[acts$statistic == statistic, ]
  }

  conditions <- unique(acts[[condition_col]])

  specific <- list()

  for (cond in conditions) {
    cond_data <- acts[acts[[condition_col]] == cond, ]

    # Find activities high in this condition
    high_in_cond <- cond_data$source[abs(cond_data$score) >= threshold]

    # Check if low in other conditions
    other_conds <- setdiff(conditions, cond)

    if (length(other_conds) > 0) {
      specific_to_cond <- c()

      for (src in high_in_cond) {
        other_scores <- acts$score[acts$source == src &
                                     acts[[condition_col]] %in% other_conds]

        if (all(abs(other_scores) < threshold)) {
          specific_to_cond <- c(specific_to_cond, src)
        }
      }

      specific[[cond]] <- specific_to_cond
    }
  }

  return(specific)
}

# ============================================================================
# Export Functions
# ============================================================================

#' Export results to CSV
#'
#' @param acts Activity results
#' @param file Output file path
#' @param statistic Filter to specific statistic (optional)
#' @export
export_results_to_csv <- function(acts, file, statistic = NULL) {
  if (!is.null(statistic) && "statistic" %in% colnames(acts)) {
    acts <- acts[acts$statistic == statistic, ]
  }

  write.csv(acts, file, row.names = FALSE)
  message(sprintf("Results exported to: %s", file))
}

#' Export results to Excel with multiple sheets
#'
#' @param acts Activity results
#' @param file Output file path
#' @param split_by Column to split into separate sheets
#' @export
export_results_to_excel <- function(acts, file, split_by = "statistic") {
  if (!requireNamespace("openxlsx", quietly = TRUE)) {
    stop("openxlsx package required for Excel export")
  }

  wb <- openxlsx::createWorkbook()

  if (split_by %in% colnames(acts)) {
    for (val in unique(acts[[split_by]])) {
      sheet_data <- acts[acts[[split_by]] == val, ]
      openxlsx::addWorksheet(wb, as.character(val))
      openxlsx::writeData(wb, as.character(val), sheet_data)
    }
  } else {
    openxlsx::addWorksheet(wb, "Results")
    openxlsx::writeData(wb, "Results", acts)
  }

  openxlsx::saveWorkbook(wb, file, overwrite = TRUE)
  message(sprintf("Results exported to: %s", file))
}

#' Export network to GMT format
#'
#' @param net Network data frame
#' @param file Output GMT file path
#' @export
export_network_to_gmt <- function(net, file) {
  sources <- unique(net$source)

  lines <- c()

  for (src in sources) {
    targets <- net$target[net$source == src]
    line <- paste(c(src, "", targets), collapse = "\t")
    lines <- c(lines, line)
  }

  writeLines(lines, file)
  message(sprintf("Network exported to GMT: %s", file))
}

# ============================================================================
# Test Data Generation
# ============================================================================

#' Create test data for decoupleR analysis
#'
#' @param n_samples Number of samples
#' @param n_genes Number of genes
#' @param n_sources Number of pathway/TF sources
#' @param seed Random seed
#' @return List with test matrix and network
#' @export
create_decoupler_test_data <- function(n_samples = 20, n_genes = 500,
                                       n_sources = 10, seed = 42) {
  set.seed(seed)

  # Create gene names
  gene_names <- paste0("GENE_", 1:n_genes)
  sample_names <- paste0("SAMPLE_", 1:n_samples)

  # Create test matrix (log-normal distribution)
  mat <- matrix(rlnorm(n_genes * n_samples, meanlog = 2, sdlog = 1),
                nrow = n_genes, ncol = n_samples)
  rownames(mat) <- gene_names
  colnames(mat) <- sample_names

  # Create test network
  net_list <- list()

  for (i in 1:n_sources) {
    source_name <- paste0("PATHWAY_", LETTERS[i])

    # Each source regulates 20-50 targets
    n_targets <- sample(20:50, 1)
    targets <- sample(gene_names, n_targets)

    weights <- runif(n_targets, 0.5, 2)
    mors <- sample(c(-1, 1), n_targets, replace = TRUE)

    net_list[[i]] <- data.frame(
      source = source_name,
      target = targets,
      weight = weights,
      mor = mors
    )
  }

  net <- do.call(rbind, net_list)

  # Add some pathway-specific signal to matrix
  for (i in 1:min(3, n_sources)) {
    source_name <- paste0("PATHWAY_", LETTERS[i])
    targets <- net$target[net$source == source_name]

    # Upregulate in first half of samples
    target_idx <- match(targets, gene_names)
    mat[target_idx, 1:(n_samples/2)] <- mat[target_idx, 1:(n_samples/2)] * 1.5
  }

  return(list(
    mat = mat,
    net = net,
    metadata = data.frame(
      sample = sample_names,
      condition = rep(c("A", "B"), each = n_samples/2)
    )
  ))
}

# ============================================================================
# Parameter Recommendation
# ============================================================================

#' Recommend decoupleR parameters based on data characteristics
#'
#' @param mat Expression matrix
#' @param net Network data frame
#' @return List with parameter recommendations
#' @export
recommend_decoupler_params <- function(mat, net) {
  recs <- list()

  # Check data size
  n_samples <- ncol(mat)
  n_genes <- nrow(mat)

  # Method recommendations
  if (n_samples < 10) {
    recs$methods <- c("ulm", "wsum")
    recs$consensus <- FALSE
    recs$note <- "Few samples; use simpler methods without consensus"
  } else if (n_samples < 50) {
    recs$methods <- c("ulm", "mlm", "wsum")
    recs$consensus <- TRUE
    recs$note <- "Moderate samples; consensus recommended"
  } else {
    recs$methods <- c("ulm", "mlm", "wsum", "aucell", "fgsea")
    recs$consensus <- TRUE
    recs$note <- "Many samples; all methods applicable"
  }

  # minsize recommendation
  overlap <- check_gene_overlap(mat, net)
  if (overlap$overlap_fraction < 0.3) {
    recs$minsize <- 3
    recs$minsize_note <- "Low overlap; use smaller minsize"
  } else {
    recs$minsize <- 5
    recs$minsize_note <- "Standard minsize"
  }

  # Center recommendation
  if (min(mat, na.rm = TRUE) >= 0) {
    recs$center <- TRUE
    recs$center_note <- "Non-negative data; centering recommended for ULM/MLM"
  } else {
    recs$center <- FALSE
    recs$center_note <- "Data appears centered already"
  }

  return(recs)
}

#' Show parameter guide
#'
#' @return Prints parameter selection guide
#' @export
show_parameter_guide <- function() {
  cat("\n=== decoupleR Parameter Guide ===\n\n")

  cat("Methods:\n")
  cat("  ULM  - Univariate Linear Model (fast, good for most cases)\n")
  cat("  MLM  - Multivariate Linear Model (accounts for network overlap)\n")
  cat("  WSum - Weighted Sum (simple, good for small datasets)\n")
  cat("  WMean - Weighted Mean (alternative to WSum)\n")
  cat("  AUCell - Area Under Curve (good for single-cell)\n")
  cat("  ORA  - Over-Representation Analysis (discrete input only)\n")
  cat("  GSVA - Gene Set Variation Analysis (good for bulk)\n")
  cat("  FGSEA - Fast GSEA (good for ranking-based analysis)\n")
  cat("  UDT  - Univariate Decision Tree (non-linear)\n")
  cat("  MDT  - Multivariate Decision Tree (non-linear with interactions)\n\n")

  cat("Common Parameters:\n")
  cat("  minsize    - Minimum targets per source (default: 5)\n")
  cat("  center     - Center expression matrix (default: FALSE)\n")
  cat("  na.rm      - Remove NA values (default: FALSE)\n")
  cat("  seed       - Random seed for reproducibility\n\n")

  cat("Consensus Score:\n")
  cat("  Combine multiple methods using median aggregation\n")
  cat("  Recommended when using 3+ methods\n\n")
}


#' Create decoupleR analysis report
#'
#' Generate a text summary report from decoupleR results
#'
#' @param acts Activity results from decoupleR
#' @param net Network data frame (optional, for network stats)
#' @param output_file Path to write report (optional)
#' @return Report string (invisible)
#' @export
create_decoupler_report <- function(acts, net = NULL, output_file = NULL) {
  # Build report lines
  lines <- character()

  lines <- c(lines, "========================================")
  lines <- c(lines, "         decoupleR Analysis Report")
  lines <- c(lines, "========================================")
  lines <- c(lines, "")
  lines <- c(lines, sprintf("Generated: %s", Sys.time()))
  lines <- c(lines, "")

  # Summary
  summary <- summarize_decoupler_results(acts)
  lines <- c(lines, "--- Summary ---")
  lines <- c(lines, sprintf("Sources (pathways/TFs): %d", summary$n_sources))
  lines <- c(lines, sprintf("Conditions (samples/cells): %d", summary$n_conditions))
  lines <- c(lines, sprintf("Total scores: %d", summary$n_scores))
  lines <- c(lines, sprintf("Methods: %s", paste(summary$methods, collapse = ", ")))
  lines <- c(lines, sprintf("Score range: %.3f to %.3f",
                            summary$score_range[1], summary$score_range[2]))
  lines <- c(lines, sprintf("Mean score: %.3f (SD: %.3f)",
                            summary$score_mean, summary$score_sd))
  if (!is.null(summary$n_significant)) {
    lines <- c(lines, sprintf("Significant (p < 0.05): %d (%.1f%%)",
                              summary$n_significant, summary$significant_fraction * 100))
  }
  lines <- c(lines, "")

  # Network stats
  if (!is.null(net)) {
    net_summary <- show_network_summary(net)
    lines <- c(lines, "--- Network ---")
    lines <- c(lines, sprintf("Sources in network: %d", net_summary$n_sources))
    lines <- c(lines, sprintf("Targets in network: %d", net_summary$n_targets))
    lines <- c(lines, sprintf("Interactions: %d", net_summary$n_interactions))
    lines <- c(lines, "")
  }

  # Top activities
  lines <- c(lines, "--- Top 10 Activities ---")
  top <- get_top_activities(acts, n_top = 10)
  lines <- c(lines, capture.output(print(top)))
  lines <- c(lines, "")
  lines <- c(lines, "========================================")
  lines <- c(lines, "End of Report")
  lines <- c(lines, "========================================")

  report_text <- paste(lines, collapse = "\n")

  # Write to file if requested
  if (!is.null(output_file)) {
    writeLines(report_text, output_file)
    message(sprintf("Report saved to: %s", output_file))
  }

  invisible(report_text)
}
